CREATE TABLE tracked_products (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id),
    provider_code VARCHAR(50) NOT NULL,
    external_id VARCHAR(120) NOT NULL,
    source_url VARCHAR(2048) NOT NULL,
    title VARCHAR(500) NOT NULL,
    normalized_title VARCHAR(500) NOT NULL,
    brand VARCHAR(120),
    model VARCHAR(120),
    color VARCHAR(80),
    storage VARCHAR(80),
    condition VARCHAR(30) NOT NULL,
    target_price NUMERIC(19, 2) NOT NULL CHECK (target_price > 0),
    currency VARCHAR(3) NOT NULL DEFAULT 'BRL',
    status VARCHAR(20) NOT NULL CHECK (status IN ('ACTIVE', 'PAUSED', 'ERROR', 'DELETED')),
    check_interval_minutes INTEGER NOT NULL CHECK (check_interval_minutes >= 5),
    last_checked_at TIMESTAMPTZ,
    next_check_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_tracked_product_user_provider_external UNIQUE (user_id, provider_code, external_id)
);
