CREATE TABLE price_snapshots (
    id UUID PRIMARY KEY,
    tracked_product_id UUID NOT NULL REFERENCES tracked_products(id),
    provider_code VARCHAR(50) NOT NULL,
    external_id VARCHAR(120) NOT NULL,
    title VARCHAR(500) NOT NULL,
    normalized_title VARCHAR(500) NOT NULL,
    price NUMERIC(19, 2) NOT NULL CHECK (price > 0),
    regular_price NUMERIC(19, 2) CHECK (regular_price IS NULL OR regular_price > 0),
    currency VARCHAR(3) NOT NULL,
    payment_type VARCHAR(30) NOT NULL CHECK (payment_type IN ('PIX', 'CREDIT_CARD', 'BOLETO', 'UNKNOWN')),
    installment_count INTEGER,
    installment_amount NUMERIC(19, 2),
    coupon_required BOOLEAN NOT NULL,
    coupon_code VARCHAR(120),
    seller_id VARCHAR(120),
    seller_name VARCHAR(255),
    condition VARCHAR(30) NOT NULL,
    color VARCHAR(80),
    storage VARCHAR(80),
    in_stock BOOLEAN NOT NULL,
    available_quantity INTEGER,
    source_url VARCHAR(2048) NOT NULL,
    observed_at TIMESTAMPTZ NOT NULL,
    fingerprint VARCHAR(64) NOT NULL,
    raw_payload JSONB
);
